//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homework3.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} flies away!.
        /// </summary>
        internal static string away_flyable {
            get {
                return ResourceManager.GetString("away_flyable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} swims away!.
        /// </summary>
        internal static string away_swimmable {
            get {
                return ResourceManager.GetString("away_swimmable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enclosure for {0} now has {1} animals.\nMembers: {2}.
        /// </summary>
        internal static string enclosure_update {
            get {
                return ResourceManager.GetString("enclosure_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} happily ate &apos;{1}&apos;..
        /// </summary>
        internal static string feeding_happy {
            get {
                return ResourceManager.GetString("feeding_happy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rejected &apos;{1}&apos;..
        /// </summary>
        internal static string feeding_reject {
            get {
                return ResourceManager.GetString("feeding_reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food &apos;{0}&apos; dropped into {1} enclosure!.
        /// </summary>
        internal static string food_dropped_enclosure {
            get {
                return ResourceManager.GetString("food_dropped_enclosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid age..
        /// </summary>
        internal static string invalid_age {
            get {
                return ResourceManager.GetString("invalid_age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid animal type selected..
        /// </summary>
        internal static string invalid_animal_type {
            get {
                return ResourceManager.GetString("invalid_animal_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jellyfish.
        /// </summary>
        internal static string jellyfish {
            get {
                return ResourceManager.GetString("jellyfish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} says {2}..
        /// </summary>
        internal static string make_sound_log {
            get {
                return ResourceManager.GetString("make_sound_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penguin.
        /// </summary>
        internal static string penguin {
            get {
                return ResourceManager.GetString("penguin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} did not like being teased. Do not tease animals..
        /// </summary>
        internal static string teasing {
            get {
                return ResourceManager.GetString("teasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} attacked you. You are loosing consciousness....
        /// </summary>
        internal static string teasing_attack {
            get {
                return ResourceManager.GetString("teasing_attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whale.
        /// </summary>
        internal static string whale {
            get {
                return ResourceManager.GetString("whale", resourceCulture);
            }
        }
    }
}
